# Generated by Django 5.1.3 on 2025-01-17 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('F', 'Fiction'), ('N', 'Non-Fiction'), ('P', 'Poetry'), ('R', 'Romantic'), ('H', 'Horror'), ('S', 'Science Fiction'), ('M', 'Mystery'), ('C', 'Comedy'), ('D', 'Drama'), ('A', 'Action'), ('T', 'Thriller'), ('G', 'General')], default='G', max_length=1),
        ),
    ]
