# Generated by Django 5.1.5 on 2025-01-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
