# Generated by Django 5.1.5 on 2025-01-31 09:19

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_rename_tags_post_story_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='story_type',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
