# Generated by Django 5.2 on 2025-06-12 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_rename_story_type_post_tags_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('F', 'Fiction'), ('N', 'Non-Fiction'), ('P', 'Poetry'), ('R', 'Romantic'), ('H', 'Horror'), ('S', 'Science Fiction'), ('M', 'Mystery'), ('C', 'Comedy'), ('D', 'Drama'), ('A', 'Action'), ('T', 'Thriller'), ('G', 'General')], default='G', max_length=5),
        ),
    ]
